fix: improve the script, die in more places

diff --git a/usr/local/bin/install-nextcloud b/usr/local/bin/install-nextcloud
--- a/usr/local/bin/install-nextcloud
+++ b/usr/local/bin/install-nextcloud
@@ -47,7 +47,7 @@ while getopts d:hH:p:P:r:u:U: opt; do
         h) help ;;
         H) DB_HOST="${OPTARG}" ;;
         p) ADMIN_PASSWORD="${OPTARG}" ;;
-        P) DB_PASS="${OPTARG}" ;;
+        P) DB_PASSWORD="${OPTARG}" ;;
         r) NEXTCLOUD_ROOT="${OPTARG}" ;;
         u) ADMIN_USERNAME="${OPTARG}" ;;
         U) DB_USER="${OPTARG}" ;;
@@ -86,11 +86,17 @@ download() {
 }
 
 download_latest() {
-    download "${NEXTCLOUD_CHECKSUM_URL}" "${NEXTCLOUD_CHECKSUM_FILE}"
+    echo "Downloading checksum file to ${NEXTCLOUD_CHECKSUM_FILE}"
+    if ! download "${NEXTCLOUD_CHECKSUM_URL}" "${NEXTCLOUD_CHECKSUM_FILE}"; then
+        die "Failed to download checksum file"
+    fi
     local checksum="$(cut -f1 -d' ' "${NEXTCLOUD_CHECKSUM_FILE}")"
 
     if test ! -f "${NEXTCLOUD_ARCHIVE_FILE}" || ! sha512 -q -c "${checksum}" "${NEXTCLOUD_ARCHIVE_FILE}"; then
-        download "${NEXTCLOUD_ARCHIVE_URL}" "${NEXTCLOUD_ARCHIVE_FILE}"
+        echo "Downloading Nextcloud archive"
+        if ! download "${NEXTCLOUD_ARCHIVE_URL}" "${NEXTCLOUD_ARCHIVE_FILE}"; then
+            echo "Failed to download installation archive"
+        fi
         if ! sha512 -q -c "${checksum}" "${NEXTCLOUD_ARCHIVE_FILE}"; then
             die "Could not validate archive ${NEXTCLOUD_ARCHIVE_FILE} using SHA512 checksum"
         fi
@@ -102,6 +108,7 @@ current_date() {
 }
 
 backup_mysql() {
+    echo "Dumping database to file"
     mysqldump --single-transaction  --default-character-set=utf8mb4 \
         -h "${DB_SERVER}" -u "${DB_USER}" -p"${DB_PASSWORD}" > "${NEXTCLOUD_INSTALL_ROOT}/${NEXTCLOUD_DB_BACKUP_FILE}"
 }
@@ -183,8 +190,13 @@ install_nextcloud_files() {
     mkdir -p "${NEXTCLOUD_ROOT}"
     chown -R "${PHP_USER}":"${PHP_USER}" "${NEXTCLOUD_ROOT}"
 
-    as_user tar -xjf "${NEXTCLOUD_ARCHIVE_FILE}" --cd "${NEXTCLOUD_ROOT}"
+    echo "Extracting new Nextcloud files..."
+    if ! as_user tar -xjf "${NEXTCLOUD_ARCHIVE_FILE}" --cd "${NEXTCLOUD_ROOT}"; then
+        die "Failed to extract Nextcloud files"
+    fi
+    echo "Extracted"
 
+    echo "Setting permissions on installed files"
     chown -R "${PHP_USER}":"${PHP_USER}" "${NEXTCLOUD_ROOT}"
     find "${NEXTCLOUD_ROOT}" -type d -exec chmod 750 {} \;
     find "${NEXTCLOUD_ROOT}" -type f -exec chmod 640 {} \;
@@ -212,9 +224,15 @@ setup_db_four_byte() {
     while true; do
         if db_cmd -e "SHOW VARIABLES LIKE 'innodb_file_per_table'" | grep ON; then
             if $run_commands; then
-                db_cmd -e "ALTER DATABASE ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci"
-                occ config:system:set mysql.utf8mb4 --type boolean --value="true"
-                occ maintenance:repair
+                if ! db_cmd -e "ALTER DATABASE ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci"; then
+                    die "Failed to set database to UTF-8 4-bytes"
+                fi
+                if ! occ config:system:set mysql.utf8mb4 --type boolean --value="true"; then
+                    die "Failed to enable UTF-8 4-bytes in Nextcloud"
+                fi
+                if ! occ maintenance:repair; then
+                    die "Failed to repair the installation after enabling UTF-8 4-bytes"
+                fi
             fi
             break
         fi
@@ -234,6 +252,7 @@ setup_db_four_byte() {
 }
 
 run_installation() {
+    echo "Running Nextcloud installation"
     occ maintenance:install --database "mysql" --database-host "${DB_HOST}" --database-name "${DB_NAME}" \
         --database-user "${DB_USER}" --database-pass "${DB_PASSWORD}" --admin-user "${ADMIN_USERNAME}" \
         --admin-pass "${ADMIN_PASSWORD}" --data-dir "${NEXTCLOUD_DATA_DIR}"
